# Generated by Django 5.2.4 on 2025-07-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True, help_text='Detailed description paragraph 1')),
                ('additional_description', models.TextField(blank=True, help_text='Additional description paragraph 2')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('secondary_image_url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon, e.g. icon-creative', max_length=100)),
                ('highlight_text_1', models.TextField(blank=True, help_text='First highlight text box')),
                ('highlight_text_2', models.TextField(blank=True, help_text='Second highlight text box')),
                ('additional_content', models.TextField(blank=True, help_text='Additional paragraph content')),
                ('benefits_title', models.CharField(default='Service Benefits', max_length=200)),
                ('benefits_description', models.TextField(blank=True, help_text='Benefits description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='consulting.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='consulting.service')),
            ],
        ),
    ]
