# Generated by Django 5.2.4 on 2025-07-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseKeypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='consulting.case')),
            ],
        ),
    ]
