# Generated by Django 5.2.4 on 2025-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for list page')),
                ('content', models.TextField(help_text='Full blog post content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
