# Generated by Django 5.2.4 on 2025-09-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0007_blogcategory_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookACall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is your name? (So we know what to call you!)', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Do you have a website we can check out? (if not, please enter N/A)', max_length=500)),
                ('email', models.EmailField(help_text="What's the best email to reach you? (We'll keep it safe and only use it to connect with you.)", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="What's your best contact number? (Only needed in case it is important to reach out quickly.)", max_length=20)),
                ('services_looking_for', models.CharField(choices=[('fundraising', 'Fundraising'), ('transaction_advisory', 'Transaction Advisory Services'), ('financial_models', 'Financial Models and Investor Documents'), ('ma_advisory', 'M&A Investment Advisory'), ('eta_support', 'ETA Support'), ('due_diligence', 'Due Diligence for a Transaction'), ('fractional_cfo', 'Fractional CFO'), ('investment_research', 'Investment Research')], help_text='Are you looking for:', max_length=50)),
                ('business_stage', models.CharField(choices=[('ideation_mvp', "Ideation to MVP (Either it's just an idea, or you just have an MVP with no traction)"), ('product_development', 'Product is developed or will be developed within 3 months - Ready to launch and need to launch and marketing.'), ('smb_revenue', 'Small and Medium Size Business Already generating revenue - Need Capital to scale'), ('large_corporate', 'Large Corporate (looking for merger, acquisition, strategic sale, expansion, and project finance)'), ('other', 'Other (PE, VC, Search Fund, Investor and Family Office)')], help_text='Which stage best describes your business at the moment?', max_length=50)),
                ('capital_amount', models.CharField(blank=True, help_text='How much capital are you looking to raise (Ballpark figure is fine, if not, please enter NA)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed when call is scheduled')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
            ],
            options={
                'verbose_name': 'Book a Call Request',
                'verbose_name_plural': 'Book a Call Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.CreateModel(
            name='BookACallGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Guest email address', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Guest name (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_a_call', models.ForeignKey(help_text='The Book a Call request this guest belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='consulting.bookacall')),
            ],
            options={
                'verbose_name': 'Book a Call Guest',
                'verbose_name_plural': 'Book a Call Guests',
                'unique_together': {('book_a_call', 'email')},
            },
        ),
    ]
